docs: add content on running public RPC node and node monitoring
nervosnetwork/docs.nervos.org pull request #177
Opened 2023-05-11 08:24 UTC by linnnsss

Updated previous essay on running a CKB mainnet node, included another approach of running a public PRC node. Also added instructions on node monitoring using CkbGuardian.

2023-05-11 08:37 UTC, gpBlockchain requested changes

2023-05-25 13:47 UTC, zhangsoledad commented on website/docs/basics/guides/mainnet.md
> +git clone https://github.com/jiangxianliang007/ckb-nginx-proxy.git
```suggestion
git clone https://github.com/cryptape/ckb-nginx-proxy.git
```

2023-05-26 01:29 UTC, linnnsss reviewed
updated content based on reviewers' comments

2023-05-26 02:19 UTC, zhangsoledad approved these changes

2023-05-29 02:43 UTC, doitian approved these changes

2023-06-08 03:32 UTC, janx approved these changes

2023-06-08 03:32 UTC, merged