Update devchain.md
nervosnetwork/docs.nervos.org pull request #202
Opened 2023-10-31 01:08 UTC by linnnsss

update account generation info and improve language

2023-10-31 01:14 UTC, 15168316096 commented
lgtm

2023-11-04 04:25 UTC, jordanmack requested changes

2023-11-04 04:25 UTC, jordanmack commented on website/docs/basics/guides/devchain.md
> -Your new account is locked with a password. Please give a password. Do not forget this password.
Same as before. Do not change because this should match the ckb-cli output.

2023-11-04 04:25 UTC, jordanmack commented on website/docs/basics/guides/devchain.md
> +gitpod /workspace/forcerelay_deployment_playground (main) $ ckb-cli account new
Start the line with "$". Remove anything specific to your local environment.

2023-11-04 04:25 UTC, jordanmack commented on website/docs/basics/guides/devchain.md
> -Your new account is locked with a password. Please give a password. Do not forget this password.
Same as the others. Do not change the output.

2023-11-07 03:42 UTC, 15168316096 commented on website/docs/basics/guides/devchain.md
> -Your new account is locked with a password. Please give a password. Do not forget this password.
The previous output is the old output, and the content needs to be updated to match the new output to facilitate user understanding. The relevant ckb-cli version is  
```
ckb-cli --version
ckb-cli 1.5.0 (f043bf1 2023-09-14)

ckb-cli account new
Your new account is locked with a password. Please give a password. Do not forget this password.
Password: 
Repeat password: 
address:
  mainnet: ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqghklqs0vttylku4pjxhr8hxsaratn8muc28r7vu
  testnet: ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqghklqs0vttylku4pjxhr8hxsaratn8mucy4g3xy
address(deprecated):
  mainnet: ckb1qyqp0d7pq7ckkflde2rydwx0wdp686hx0hesvfqn3l
  testnet: ckt1qyqp0d7pq7ckkflde2rydwx0wdp686hx0hes3v7var
lock_arg: 0x17b7c107b16b27edca8646b8cf7343a3eae67df3
lock_hash: 0x9fecea1600fecfac989b2d15dc227b885afe68f5b652a1a159b59cb69e83ddae
```

2023-11-07 04:45 UTC, jordanmack commented on website/docs/basics/guides/devchain.md
> -Your new account is locked with a password. Please give a password. Do not forget this password.
I think we are in agreement. The text in the guide needs to match the output of `ckb-cli`. The correct text is:

`Your new account is locked with a password. Please give a password. Do not forget this password.`

2023-11-15 03:03 UTC, merged