add 2nd batch of tech terms
nervosnetwork/docs.nervos.org pull request #369
Opened 2024-06-14 03:38 UTC by linnnsss

add the 2nd batch of tech terms under "tech explanation"

2024-06-14 06:31 UTC, RetricSu commented on website/sidebars.js
> +        "tech-explanation/script-group-exe",
please move "tech-explanation/witness" here, it is more important

2024-06-14 08:52 UTC, yfeng2824 requested changes

2024-06-14 08:52 UTC, yfeng2824 commented on website/docs/tech-explanation/outputs.md
> +The transaction destroys the Cells in inputs and creates the Cells in outputs. These output Cells, identical in structure as the aforementioned [Cell structure](#cell-structure), can be used as input
```suggestion
The transaction destroys the Cells in inputs and creates the Cells in outputs. These output Cells, identical in structure as the aforementioned [Cell structure](/docs/tech-explanation/cell#cell-structure), can be used as inputs for future transactions.
```

2024-06-17 07:27 UTC, yfeng2824 approved these changes

2024-06-17 07:27 UTC, merged